name: WebGL Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          buildsPath: Build
          buildName: Build
          buildMethod: UnityCiPipeline.CustomBuildPipeline.RunBuildForVersion
          customParameters: -buildTarget WebGL -version testVer
          versioning: None
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Build
